# SPDX-License-Identifier: GPL-2.0

dtbo-y += exynos9610-a50_swa_open_00.dtbo
dtbo-y += exynos9610-a50_swa_open_01.dtbo
dtbo-y += exynos9610-a50_swa_open_02.dtbo
dtbo-y += exynos9610-a50_swa_open_03.dtbo
dtbo-y += exynos9610-a50_swa_open_04.dtbo
dtbo-y += exynos9610-a50_swa_open_06.dtbo

always := $(dtbo-y)

clean-files := *.dtb *.dtbo
